"""settings"""

SCREEN_HEIGHT = 500
SCREEN_WIDTH = 700

BOTTOM = SCREEN_HEIGHT
TOP = 0
RIGHT = SCREEN_WIDTH
LEFT = 0

BORDER_BUFFER = 3

LASER_DURATION = 0.1 #seconds

BACKGROUND_COLOR = (0,0,0)
ASTEROID_COLOR = (0,0,0)
DEATH_COLOR = (0,0,255)

ASTEROID_SPAWN_RATE = 5
ASTEROID_DAMAGE_RATE = 0.5

NUM_STARS = 500